global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'statsd-exporter'
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: ['statsd-exporter:9102']
