{
 "title": "General Resources",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "N|Solid",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=https://assets.nodesource.com/nsolid-logo-light.svg>"
   }
  },
  { "title": "SERVER RESOURCES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nsolid_statsd_cpuPercent", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nsolid_statsd_freeMem", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "SERVER CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nsolid_statsd_cpuSystemPercent", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "HTTP REQUEST SERVER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nsolid_statsd_httpServerCount", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "HTTP REQUEST CLIENT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nsolid_statsd_httpClientCount", "legendFormat": "{{app}}" }
   ]
  }
 ]
}