{
 "title": "Process",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "processId",
    "label": "Process Id",
    "query": {
     "query": "label_values({app=\"$app\"},shortId)"
    }
   },
   { "name": "app", "label": "Application Name", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "N|Solid",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=https://assets.nodesource.com/nsolid-logo-light.svg>"
   }
  },
  {
   "title": "Internal Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nsolid_statsd_gcCount{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "GC COUNT"
    },
    {
     "expr": "nsolid_statsd_loopTotalCount{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "LOOP COUNT"
    }
   ]
  },
  {
   "title": "EVENT LOOP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nsolid_statsd_loopEstimatedLag{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "LAG"
    },
    {
     "expr": "nsolid_statsd_loopIdlePercent{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "IDLE%"
    }
   ]
  },
  {
   "title": "ELU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nsolid_statsd_loopUtilization{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "{{app}}({{shortId}})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "description": "$app($processId)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nsolid_statsd_heapUsed{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "HEAP"
    },
    {
     "expr": "nsolid_statsd_rss{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "nsolid_statsd_externalMem{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "EXTERNAL"
    }
   ]
  },
  {
   "title": "PROCESS CPU USAGE",
   "type": "timeseries",
   "description": "ProcessId: $processId",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nsolid_statsd_cpuUserPercent{app=\"$app\", shortId=\"$processId\"}",
     "legendFormat": "{{app}}({{hostname}})"
    }
   ]
  }
 ]
}